### ISSUE TITLE
Percona wrong memory calculation

### ISSUE THREAD

**Issue by m0rdice** [major/MySQLTuner-perl#456] opened 2019-09-30 09:18 UTC
Hi guys,

we have a problem with the MySQLTuner memory calculation.

# Server details
```
OS: Ubuntu 16.04 LTS
MySQLTuner: 1.7.16
Database: percona-xtradb-cluster-server-5.7 (5.7.26-31.37-1.xenial)
Type: Galera Cluster
wsrep_provider_version: 3.37(rff05089)
```

# Problem

## Example 1
MySQLTuner:
```
-------- Performance Metrics -----------------------------------------------------------------------
[OK] Maximum reached memory usage: 42.3G (67.56% of installed RAM)
[OK] Maximum possible memory usage: 42.7G (68.27% of installed RAM)
```

htop:
```
   PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
319809 mysql      20   0 65.1G 48.9G  836M S 1523 78.1 86h59:56 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --wsrep-provider=/usr/lib/libgalera_smm.so --log-error=/var/log/mysql/error.log --open-files-limit=3276
```

## Example 2
MySQLTuner:
```
-------- Performance Metrics -----------------------------------------------------------------------
[OK] Maximum reached memory usage: 16.3G (34.67% of installed RAM)
[OK] Maximum possible memory usage: 16.8G (35.69% of installed RAM)
```

htop:
```
   PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
  9040 mysql      20   0 36.4G 33.3G 25524 S  4.0 70.5 99h29:53 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --wsrep-provider=/usr/lib/libgalera_smm.so --log-error=/var/log/mysql/error.log --open-files-limit=32768
```

Whats wrong here?

Thanks!
 Patrick

**Comment by jmrenouard** [comment] 2019-10-03 21:23
Duplicate of 
MySQL memory usage exceeding "Maximum Possible Memory Usage" #378

**Comment by m0rdice** [comment] 2019-11-28 08:44
Hi @jmrenouard,

any ideas why this happens or do you know when this bug is fixed?


Kind regards,
 Patrick

**Closed** 2020-01-08 19:48 UTC
Labels: Help Wanted, bug
