### ISSUE TITLE
Difference memory usage between versions

### ISSUE THREAD

**Issue by th1m0r** [major/MySQLTuner-perl#546] opened 2021-02-25 11:48 UTC
Hi,
I am using madiadb 10.5.8 on archlinux. I did installed mysqltuner using pacman. Recently i did download a new version using the instructions of this page. After run new version the values of memory did very different with same configuration file. This is normal?

 >>  MySQLTuner 1.7.15 - Major Hayden <major@mhtx.net>
[--] Physical Memory     : 23.5G
[--] Max MySQL memory    : 17.8G
[--] Other process memory: 0B
[--] Total buffers: 16.4G global + 28.2M per thread (50 max threads)
[--] P_S Max memory usage: 72B
[--] Galera GCache Max memory usage: 0B
[OK] Maximum reached memory usage: 17.0G (72.28% of installed RAM)
[OK] Maximum possible memory usage: 17.8G (75.68% of installed RAM)

 >>  MySQLTuner 1.7.21 - Major Hayden <major@mhtx.net>
[--] Physical Memory     : 23.5G
[--] Max MySQL memory    : 67.8G
[--] Other process memory: 0B
[--] Total buffers: 16.4G global + 1.0G per thread (50 max threads)
[--] P_S Max memory usage: 72B
[--] Galera GCache Max memory usage: 0B
[!!] Maximum reached memory usage: 38.0G (161.75% of installed RAM)
[!!] Maximum possible memory usage: 67.8G (288.70% of installed RAM)

[mysqld]
performance_schema = ON

datadir=/var/lib/mysql/data

default-storage-engine=INNODB

sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"

lower_case_table_names = 1

max_connections=50
table_open_cache=10000
open_files_limit=10000
table_definition_cache=-1
tmp_table_size=256M
max_heap_table_size=256M

key_buffer_size         = 8M
max_allowed_packet      = 1G
thread_stack            = 192K
net_buffer_length       = 1M

sort_buffer_size=2M
read_buffer_size=2M
read_rnd_buffer_size=8M
join_buffer_size=16M

thread_cache_size       = 16

query_cache_type        =0
query_cache_size        =0

innodb_read_io_threads=16
innodb_write_io_threads=16
innodb_buffer_pool_size=16G
innodb_log_file_size=4G
innodb_log_buffer_size=4M
innodb_flush_log_at_trx_commit=2
innodb_thread_concurrency=16
innodb_open_files=1024
innodb_file_per_table=1

skip-name-resolve=1

[mysqldump]
quick
quote-names
max_allowed_packet      = 1G

**Comment by birdie-github** [comment] 2021-02-25 16:00
It's even worse for me:

1.7.17
```
[OK] Maximum reached memory usage: 41.2G (65.83% of installed RAM)
[OK] Maximum possible memory usage: 48.7G (77.82% of installed RAM)
[OK] Overall possible memory usage with other process is compatible with memory available
```

1.7.21
```
[!!] Maximum reached memory usage: 615.2G (982.79% of installed RAM)
[!!] Maximum possible memory usage: 1248.7G (1994.81% of installed RAM)
[!!] Overall possible memory usage with other process exceeded memory
```

**Comment by rickschippers** [comment] 2022-02-28 09:28
@th1m0r the issue is:

max_allowed_packet = 1G

Older version did not include this in the max memory calculation, newer versions do. This is multiplied by max_connections since this is per connection. So in your case this will lead to a 50GB difference in the max memory.

**Comment by jmrenouard** [comment] 2023-06-18 20:06
Issue fixed with last PR: Fixing wrong calculation in memory usage (regression found) #679

Thanks for your patience and reporting this issue
 @jmrenouard

**Closed by jmrenouard** 2023-06-18 20:06 UTC
