### ISSUE TITLE
MySQL's maximum memory usage is dangerously high

### ISSUE THREAD

**Issue by zoddshop** [major/MySQLTuner-perl#673] opened 2023-06-12 12:19 UTC
How is this adding up to 1 gig per thread???

[--] Total buffers: 32.2G global + 1.0G per thread (500 max threads)
[--] Performance_schema Max memory usage: 148M
[--] Galera GCache Max memory usage: 0B
[!!] Maximum reached memory usage: 221.2G (176.08% of installed RAM)
[!!] Maximum possible memory usage: 534.6G (425.54% of installed RAM)

+-------------------------------------+----------------+
| Variable_name                       | Value          |
+-------------------------------------+----------------+
| aria_pagecache_buffer_size          | 134217728      |
| aria_sort_buffer_size               | 268434432      |
| bulk_insert_buffer_size             | 8388608        |
| innodb_buffer_pool_chunk_size       | 134217728      |
| innodb_buffer_pool_dump_at_shutdown | ON             |
| innodb_buffer_pool_dump_now         | OFF            |
| innodb_buffer_pool_dump_pct         | 25             |
| innodb_buffer_pool_filename         | ib_buffer_pool |
| innodb_buffer_pool_load_abort       | OFF            |
| innodb_buffer_pool_load_at_startup  | ON             |
| innodb_buffer_pool_load_now         | OFF            |
| innodb_buffer_pool_size             | 34359738368    |
| innodb_change_buffer_max_size       | 25             |
| innodb_change_buffering             | none           |
| innodb_log_buffer_size              | 16777216       |
| innodb_sort_buffer_size             | 1048576        |
| join_buffer_size                    | 2097152        |
| join_buffer_space_limit             | 2097152        |
| key_buffer_size                     | 16777216       |
| mrr_buffer_size                     | 262144         |
| myisam_sort_buffer_size             | 134216704      |
| net_buffer_length                   | 16384          |
| preload_buffer_size                 | 32768          |
| read_buffer_size                    | 131072         |
| read_rnd_buffer_size                | 262144         |
| sort_buffer_size                    | 2097152        |
| sql_buffer_result                   | OFF            |
+-------------------------------------+----------------+

**Comment by longradix** [comment] 2023-06-18 13:32
Is this a duplicate of #487? If not, how is it different?

**Comment by jmrenouard** [comment] 2023-06-18 20:06
Issue fixed with last PR: Fixing wrong calculation in memory usage (regression found) #679

Thanks for your patience and reporting this issue
 @jmrenouard

**Closed by jmrenouard** 2023-06-18 20:06 UTC
