### ISSUE TITLE
InnoDB Write Log efficiency exceeds 100%

### ISSUE THREAD

**Issue by Disassembler0** [major/MySQLTuner-perl#385] opened 2018-06-29 07:58 UTC
This is related to #182, #146 and overall method how the efficiency is calculated since 6dae07a. On my instance which is mainly writing (updating) rows, MySQLTuner reports `[!!] InnoDB Write Log efficiency: 115.5% (1121864 hits/ 971289 total)`. While it sounds awesome, I doubt it's true.

Relevant part of debug log:
```
[DG] V: Innodb_log_write_requests = 971324
[DG] V: Innodb_log_writes = 2093233
```

Full log attached - [mysqltuner.log](https://github.com/major/MySQLTuner-perl/files/2148220/mysqltuner.log)

**Comment by MichaIng** [comment] 2021-03-12 13:44
I can confirm this on all my systems with current MariaDB 10.5.9:
```
[DG] V: Innodb_log_write_requests = 240654
[DG] V: Innodb_log_writes = 1174937
[!!] InnoDB Write Log efficiency: 389.77% (933783 hits/ 239572 total)
```
I verified via MariaDB console that the values are correct but the interpretation seems to be not, or MariaDB suffers from a bug:
```
| Innodb_background_log_sync                  | 606071     |
| Innodb_log_waits                            | 0          |
| Innodb_log_write_requests                   | 240735     |
| Innodb_log_writes                           | 1177784    |
| Innodb_os_log_fsyncs                        | 1177755    |
| Innodb_os_log_pending_fsyncs                | 0          |
| Innodb_os_log_pending_writes                | 0          |
| Innodb_os_log_written                       | 3578370560 |
| Innodb_available_undo_logs                  | 128        |
| Innodb_onlineddl_rowlog_rows                | 0          |
| Innodb_onlineddl_rowlog_pct_used            | 0          |
| Innodb_encryption_n_rowlog_blocks_encrypted | 0          |
| Innodb_encryption_n_rowlog_blocks_decrypted | 0          |
```
From the KB: https://mariadb.com/kb/en/innodb-status-variables/#innodb_log_write_requests
> Innodb_log_write_requests
> - Description: Number of requests to write to the InnoDB redo log.
> - Scope: Global
> - Data Type: numeric
>
> Innodb_log_writes
> - Description: Number of writes to the InnoDB redo log.
> - Scope: Global
> - Data Type: numeric

Seems to be not logic that the number of write requests is much lower than the number of writes.

Related topic on StackExchange: https://dba.stackexchange.com/questions/194832/innodb-write-log-efficiency-above-100
Not really an explanation contained. That would need to be forwarded to MariaDB or InnoDB devs to get clarification about the meaning of those two stats.

**Comment by jmrenouard** [comment] 2022-03-28 21:11
I close this issue because MT isn't taking into account MariaDB bug

For more information MariaDB Jira is here: 
https://jira.mariadb.org/projects/MDEV/issues/MDEV-27354?filter=allopenissues

**Closed by jmrenouard** 2022-03-28 21:11 UTC
Labels: bug, Test wanted, Help Wanted, Wont be Fixed

**Comment by MichaIng** [comment] 2022-03-29 11:04
I guess the link issue is wrong? At least I do not see it being related. But I agree there is a bug or at least non-intuitive behaviour in MariaDB and I do not see any way to show the InnoDB write log efficiency correctly currently. To avoid confusion, probably it could be just hidden instead on MariaDB until an upstream solution is available? Better to hide info than to show wrong info.

**Comment by rjasdf** [comment] 2022-04-28 05:26
I have seen cases over 100% for MySQL versions 5.0, 5.1, 5.5, 5.6, and 5.7, but not (yet) in 8.0.

I suggest that the two metrics are not quite what they seem.  I recommend removing the check from the tuner.

**Comment by MichaIng** [comment] 2022-04-28 11:08
Good to know that MySQL (at least older versions) is affected as well. Indeed these variables seem to be misinterpreted then, rendering the current log write efficiency metric wrong.

**Comment by MichaIng** [comment] 2023-03-20 16:46
Btw, with MariaDB v10.11 I do not see values >100% anymore either, but as expected values closely below 100%. So looks like it has been fixes in recent versions of MariaDB as well as MySQL and the check can hence stay in MySQLTuner.

**Comment by berarma** [comment] 2024-02-18 22:51
I think this could be fixed for older versions. Not only gives a wrong value but it also makes wrong suggestion.
