### ISSUE TITLE
User 'user_name@localhost' has no password set.

### ISSUE THREAD

**Issue by karek314** [major/MySQLTuner-perl#268] opened 2016-11-09 20:45 UTC
Latest version from mysqltuner.com

`User 'user_name@localhost' has no password set.`

Gives this warning even when there IS password set, it happens after i have updated password for this user.

**Comment by jmrenouard** [comment] 2016-11-12 17:29
Hi @karek314 

can you send us result from 
DESC mysql.user;

**Comment by karek314** [comment] 2016-11-12 17:50
Hi,
I need also to add that this issue happens for 2 other users as well.
Here is what you have asked for, trimmed
<img width="765" alt="screen shot 2016-11-12 at 18 48 52" src="https://cloud.githubusercontent.com/assets/9548618/20239767/c4d580be-a908-11e6-9cba-44380ebbb3fd.png">

**Comment by jmrenouard** [comment] 2016-11-12 21:16
Hi @karek314 

Can you perform following query ?

Select user, host from mysql.user where Password is NULL or Password ='';

@jmrenouard

**Comment by karek314** [comment] 2016-11-12 22:08
It shows the same users which has been displayed in mysqltuner output.

But
`Select user, host from mysql.user where Password is NULL;` - Gives empty result

and

`Select user, host from mysql.user where Password = '';` - Display those users mentioned before

Which is more interesting
`SELECT * FROM `user``
Shows that those users passwords are empty, but in fact i can not access databases with those users without providing correct password. Obviously password is set but not sure why `SELECT` returns wrong result. I have tried manually changing passwords via command line as well with phpmyadmin.

```
Server version: 10.0.28-MariaDB-1~trusty - mariadb.org binary distribution
Phpmyadmin Version information: 4.5.4.1deb2ubuntu2
```

**Comment by acs-ferreira** [comment] 2016-11-30 13:56
If you
```
SET PASSWORD FOR 'user_name'@'localhost' = PASSWORD('th_pass_you_want');
FLUSH PRIVILEGES;
```
Does it helps?

**Comment by karek314** [comment] 2016-11-30 14:31
I've tried to change password this way as well. Which is weird it always return that password is empty, not sure if this is some new kind of security measure in new MariaDB or what, password is there, can't log in without password or with wrong password but it always returns that is empty when `SELECT`.

**Comment by acs-ferreira** [comment] 2016-11-30 14:51
I'm using **MariaDB 10.1.19** and no having that issue.
```
dba@db-a:~$ mysql -V
mysql  Ver 15.1 Distrib 10.1.19-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**Comment by karek314** [comment] 2016-11-30 16:59
mysql  Ver 15.1 Distrib 10.0.28-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by untamed0** [comment] 2016-12-10 01:49
I've exactly the same issue. Both mysqltuner and `Select user, host from mysql.user where Password is NULL or Password ='';` returns the users with 'no password'.

However, a password is set as I can't login with an empty or incorrect password.

Also same version (latest on Debian 8 repo):
`mysql  Ver 15.1 Distrib 10.0.28-MariaDB, for debian-linux-gnu (x86_64) using readline 5.`

**Comment by tssajo** [comment] 2016-12-13 10:35
@jmrenouard I know the solution to this problem:

( from http://stackoverflow.com/questions/30692812/mysql-user-db-does-not-have-password-columns-installing-mysql-on-osx )

The important part is this: "In MySQL 5.7, the password field in mysql.user table was removed, now the field name is 'authentication_string'."

This is the case with MariaDB 10.1 too, NOT just MySQL 5.7 !

Please also note that if you upgrade from an older MySQL version to a newer MariaDB version then in the users table some users will have password hashes stored the old way (still in the password column) and newly added/modified users will have their passwords stored in the new authentication_string column (and these newly added/modified users will have their password field empty).

So I would first try to do a query like this:
```
SELECT `user`,`host` from `mysql`.`user` WHERE (`password` IS NULL OR `password`='') AND (`authentication_string` IS NULL OR `authentication_string`='');
```
If the above query ran fine then I would use its results.
If the above query failed with an error, that probably means that the user table does not have an authentication_string column (it's older MySQL version) so in that case (and only in that case!!) I would fall back to this (original) query:
```
SELECT `user`,`host` from `mysql`.`user` WHERE `password` IS NULL OR `password`='';
```

I hope this helps.

**Comment by untamed0** [comment] 2016-12-13 10:39
I can confirm @tssajo 's proposed fix works on my setup.

**Comment by tssajo** [comment] 2016-12-13 10:55
@untamed0 Thanks for testing it. But there is more to this. See this issue is essentially the same: https://github.com/major/MySQLTuner-perl/issues/234

From the linked issue, you can see that in some MySQL versions there is no password column in the user table. :) So we really should check for the following three cases:

1.) There is both password and authentication_string columns in the user table -- this is the "mixed" situation (this is the case with my MariaDB 10.1 which I "upgraded" from MySQL 5.6)

2.) There is authentication_string column but there is no password column anymore (this is reportedly the case with new MySQL 5.7.x installs)

3.) There is password column but there is no authentication_string column (this is the legacy case, older MySQL versions use this)

So using just two queries as I suggested above won't suffice. All three cases must be handled.

**Comment by jmrenouard** [comment] 2016-12-27 16:53
Is there anyone of us can provide us a PR for that ?

Thanks by advance

**Comment by Quix0r** [comment] 2017-02-15 09:46
I have same error message for accounts that has a password set (for sure).

My database version:
_10.0.29-MariaDB-0+deb8u1 - (Debian)_ 

The table `user` seem to be changed, passwords are no longer stored in column `Password`, but in `authentication_string` instead. Plus the column `plugin` is set to **mysql_native_password**.

**Comment by Quix0r** [comment] 2017-02-15 09:48
I can pastebin somewhere the output of `DESCRIBE user` ...

**Comment by meteotest-web** [comment] 2017-12-20 10:00
We also get this message for a few select users, upon investigation of the user table it looks exactly like Quix0r mentioned:
> The table user seem to be changed, passwords are no longer stored in column Password, but in authentication_string instead. Plus the column plugin is set to mysql_native_password.

`# mysql -V
mysql  Ver 15.1 Distrib 10.1.28-MariaDB, for FreeBSD10.3 (amd64) using readline 5.1`

**Comment by martinellimarco** [comment] 2018-01-18 06:27
Same here, passwords are now stored in the authentication_string column, not the password column
mysql  Ver 15.1 Distrib 10.0.33-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by jmrenouard** [comment] 2018-03-19 15:36
Hi

Some feedback ?

**Comment by meteotest-web** [comment] 2018-03-22 12:13
That seems to have done the trick, no longer complains about accounts that have a password set. Didn't test if it would pick up if an user really didn't have a password set though.

**Comment by jmrenouard** [comment] 2018-09-25 14:52
Hi,

I will close this issue because no body seems to complaint about it !

Feel free to reopen it if needed.

BR.

**Closed by jmrenouard** 2018-09-25 14:52 UTC
Labels: Help Wanted, bug
