### ISSUE TITLE
innodb_buffer_pool_instances wrong error

### ISSUE THREAD

**Issue by JeGr** [major/MySQLTuner-perl#77] opened 2015-06-18 14:59 UTC
Hi,

I get 

    [!!] InnoDB buffer pool <= 1Go and innodb_buffer_pool_instances(=1).

and to adjust

    innodb_buffer_pool_instances (=1)

Looking at the source of mysqltuner.pl, the calculation - as well as the documentation from maria or mysql - is:

Buffer Pool Size (in GB) / 1GB = Buffer Pool Instances (instances should be roughly 1GB in size).

My configuration is exactly that:

    innodb_buffer_pool_size         = 4G
    innodb_buffer_pool_instances    = 4

your code for that is

    			and $myvar{'innodb_buffer_pool_instances'} != int($myvar{'innodb_buffer_pool_size'}/(1024*1024*1024))

Perhaps a problem in size conversion or display value? Running is MariaDB 5.5.44, Ubuntu 14.04LTS.

**Comment by major** [comment] 2015-06-18 15:09
Hmm, that was just added by @jmrenouard.  I'm unable to look this over right now.

Could you take another look at this for us, @jmrenouard?  Thanks.

**Comment by cloos** [comment] 2015-06-18 15:49
@jmrenouard by the way, can you please change the 1Go to 1G. I fixed it in 1e7fe0d but a2d1135 added another one.

**Comment by major** [comment] 2015-06-18 15:59
@cloos Fixed the Go stuff in 4a5a4a3d6698a9293f36ed72283bc49a89595307

**Comment by howl** [comment] 2015-06-24 18:48
The problem is that the conditions are bad. The first conditional takes buffer_pool > 1GiB and also pool_instances != to the value converted to integer of buffer_pool in GiB.

Then the else of the same conditional assumes that buffer_pool is > 1 GiB and that is wrong because it can also enter there with buffer_pool > 1 GiB, if we have the correct settings the else will enter also with buffer_pool > 1 GiB and instances the integer value of buffer_pool in GiB.

The best way to deal with this in with the less code as possible could be only one conditional like this if if ($myvar{'innodb_buffer_pool_instances'} != max(1,int($myvar{'innodb_buffer_pool_size'}/(1024*1024*1024)))
     goodprint "InnoDB buffer pool instances: ".$myvar{'innodb_buffer_pool_instances'}."\n";
else
     badprint "InnoDB buffer pool instances: ".$myvar{'innodb_buffer_pool_instances'}."\n";
     push(@adjvars,"innodb_buffer_pool_instances(=".max(1,int($myvar{'innodb_buffer_pool_size'}/(1024*1024*1024))).")");

Don't know if it exists a function like max in perl but it's just to show the idea, also perhaps it could be interesting to mind about if the buffer_pool value is ok before.

**Comment by jmrenouard** [comment] 2015-07-01 09:30
Last commit contains a fix for this issue:

This 5 tests I have done on this point. I think this is working with 
https://github.com/major/MySQLTuner-perl/pull/78

Test1:
innodb_buffer_pool_size         = 2G
innodb_buffer_pool_instances    = 2
Result: No Warning

Test2:
innodb_buffer_pool_size         = 2G
innodb_buffer_pool_instances    = 1

Result: 
Variables to adjust:
    innodb_buffer_pool_instances(=2)

Test3:
innodb_buffer_pool_size         = 256M
innodb_buffer_pool_instances    = 1

Result: No Warning

Test4:
innodb_buffer_pool_size         = 2G
innodb_buffer_pool_instances    = 4

Result: 
Variables to adjust:
    innodb_buffer_pool_instances(=2)


Test5:
innodb_buffer_pool_size         = 256M
innodb_buffer_pool_instances    = 4

Result: 
Variables to adjust:
    innodb_buffer_pool_instances(=1)

**Comment by howl** [comment] 2015-07-06 21:58
Actual master has wrong code.

**Closed** 2015-07-10 12:13 UTC
