### ISSUE TITLE
`innodb_log_file_size` bad calculation?

### ISSUE THREAD

**Issue by solracsf** [major/MySQLTuner-perl#560] opened 2021-08-01 15:18 UTC
- MySQL 8.0.26
- MySQLTuner 1.8.1

Script outputs

```
-------- InnoDB Metrics ----------------------------------------------------------------------------
[--] InnoDB is enabled.
[--] InnoDB Thread Concurrency: 0
[OK] InnoDB File per table is activated
[OK] InnoDB buffer pool / data size: 20.0G/10.1G
[!!] Ratio InnoDB log file size / InnoDB Buffer pool size (60 %): 1.0G * 12/20.0G should be equal to 25%
[!!] InnoDB buffer pool instances: 16
[--] Number of InnoDB Buffer Pool Chunk : 160 for 16 Buffer Pool Instance(s)
[OK] Innodb_buffer_pool_size aligned with Innodb_buffer_pool_chunk_size & Innodb_buffer_pool_instances
[OK] InnoDB Read buffer efficiency: 100.00% (109245158696 hits/ 109245535688 total)
[!!] InnoDB Write Log efficiency: 72.28% (43980142 hits/ 60850178 total)
[OK] InnoDB log waits: 0.00% (0 waits / 16870036 writes)

Variables to adjust:
    innodb_log_file_size should be (=426M) if possible, so InnoDB total log files size equals to 25% of buffer pool size.
    innodb_buffer_pool_instances(=20)
```

Why recommend `426M` here?

**Comment by qeepcologne** [comment] 2021-08-11 15:29
i' with you, it's a trade-off between throughput and crash recovery time, it depends on requirements, general recommendation is not possible:

https://www.percona.com/blog/2008/11/21/how-to-calculate-a-good-innodb-log-file-size/
https://www.percona.com/blog/2016/05/31/what-is-a-big-innodb_log_file_size/
https://www.percona.com/blog/2017/10/18/chose-mysql-innodb_log_file_size/

**Comment by acsfer** [comment] 2021-08-11 17:02
I'm talking about calculation, not the recommendation itself. :)

**Comment by MichaIng** [comment] 2022-01-23 18:52
`426 MiB * 12 / 20 GiB = 25%` as advised, or the other way round: `1 GiB * 25%/60% = 426 MiB` (ignoring rounding errors). Just not sure why it takes `12` here while it's 16 buffer pool instances currently applied and 20 recommended 🤔.

**Comment by jmrenouard** [comment] 2023-06-22 08:26
Hi,

I will close this issue because this is not a bug
All is correctly calculated
And Link are ok for me, more innodb log file means longer crash recovery time at startup

In fact, this is only a simple basic advisor and you should be aware of what happens when changing settings

I will add a message, telling that high value means higher recovery crash time

**Closed** 2023-06-22 14:38 UTC
