### ISSUE TITLE
Invalid selectivity warning for MYISAM fulltext indexes

### ISSUE THREAD

**Issue by willamowius** [major/MySQLTuner-perl#156] opened 2016-02-20 13:23 UTC
When running mysqltuner with --idxstat, all MYISAM fulltext indexes show a bad selectivity warning, because it seems Mysql (5.5.47 in my case) always shows a cardinality of 1 for them in INFORMATION_SCHEMA.STATISTICS.

I believe fulltext indes should be excluded from these warnings.

**Comment by jmrenouard** [comment] 2016-02-21 16:37
Ok 
Is somebody can confirm that ?

I will avoid this for 5.5 version if confirmed

**Comment by jmrenouard** [comment] 2016-02-24 19:22
Can I close it ?

**Comment by willamowius** [comment] 2016-02-24 19:31
I would prefer if not all index stats would be skipped, but only the fulltext indexes. The cardinality of non-fulltext indexes seems ok, even in 5.5.x.

**Comment by jmrenouard** [comment] 2016-03-03 12:52
how can you find non-fulltext indexes on 5.5 ?

**Comment by willamowius** [comment] 2016-03-03 13:32
When I do a

select * from INFORMATION_SCHEMA.STATISTICS where table_name="foo" and INDEX_TYPE = "BTREE"

I only get the regular indexes and CARDINALITY seems OK.

When I select for INDEX_TYPE="FULLTEXT", I see my fulltext index, but with CARDINALITY = 1.

As far as I know, even the latest MySQL versions only support FULLTEXT indexes on MyISAM tables.

So maybe you do a  WHERE INDEX_TYPE <> "FULLTEXT" in mysqltuner ?

**Comment by cloos** [comment] 2016-03-03 13:47
Am 03.03.2016 um 14:32 schrieb Jan Willamowius:
> As far as I know, even the latest MySQL versions only support FULLTEXT
> indexes on MyISAM tables.

MySQL 5.6 supports InnoDB fulltext index ;-)
https://dev.mysql.com/doc/refman/5.6/en/innodb-fulltext-index.html

**Comment by jmrenouard** [comment] 2016-03-07 14:45
Hi everybody,

Is it ok if I add  =>WHERE INDEX_TYPE <> "FULLTEXT"<= restriction for 5.5- version ?

Thanks for your feedback.
J.M

**Comment by willamowius** [comment] 2016-03-07 20:27
Fine by me.

**Comment by jmrenouard** [comment] 2016-03-14 11:11
Ok I just fixed this issue.

Can you give us your feedback ?

**Comment by jmrenouard** [comment] 2016-03-16 14:26
I closed this issue.

**Comment by willamowius** [comment] 2016-03-19 09:10
Sorry for the delay: Now all fulltext indexes are skipped on 5.5, but --idxstat doesn't print any index, even so I do have other indexes (but probably all with good selectivity). Not sure if thats the intended bahavior.

**Comment by jmrenouard** [comment] 2016-03-22 14:32
Ok I have push a fix on one of my last commits.

It seems to be better now.

I add a hard control over all request sent to server.

**Comment by willamowius** [comment] 2016-03-22 14:41
Much better now! Works as expected.

**Closed** 2016-03-22 14:41 UTC
Labels: bug

**Comment by jmrenouard** [comment] 2016-03-22 16:57
Thanks for your feedback !
