### ISSUE TITLE
calculation bug?

### ISSUE THREAD

**Issue by logger55** [major/MySQLTuner-perl#475] opened 2020-01-29 06:15 UTC
centos 7 - the server is the same:
mysql  Ver 15.1 Distrib 10.1.43-MariaDB, for Linux (x86_64) using readline 5.1
mysqltuner-1.7.13-1.git.59e5f40.el7 from repo shows:
[OK] Maximum reached memory usage: 14.8G (23.65% of installed RAM)
[OK] Maximum possible memory usage: 35.4G (56.52% of installed RAM)

but if 
wget -O mysqltuner.pl https://raw.githubusercontent.com/major/MySQLTuner-perl/master/mysqltuner.pl
mysqltuner.pl - Version 1.7.19 shows:
[!!] Maximum reached memory usage: 103.3G (165.16% of installed RAM)
[!!] Maximum possible memory usage: 385.4G (616.17% of installed RAM)

**Comment by YogSottot** [comment] 2020-02-01 10:03
I believe that the reason for this is: https://github.com/major/MySQLTuner-perl/commit/c5765f02133259b40d9932eb7d35ba5c1665bad9

**Comment by ibaldonl** [comment] 2020-06-08 22:22
Looking at the commit, it doesn't look like a bug and it shouldn't have an effect in "Maximum reached memory usage" but only on "Maximum possible memory usage".

Do you see differences in the "Maximum reached memory usage" if you run both MySQLTuner versions at the same time?

**Comment by jmrenouard** [comment] 2023-06-18 20:04
Issue fixed with last PR: Fixing wrong calculation in memory usage (regression found) #679

Thanks for your patience and reporting this issue
 @jmrenouard

**Closed by jmrenouard** 2023-06-18 20:04 UTC
Labels: bug, Help Wanted
