### ISSUE TITLE
FAIL Execute SQL / return code: 256

### ISSUE THREAD

**Issue by tholu** [major/MySQLTuner-perl#427] opened 2019-03-08 15:08 UTC
I'm getting the following error message(s) when running the script:

```
[!!] failed to execute: SELECT CONCAT(user, '@', host) FROM mysql.user WHERE IF(plugin='mysql_native_password', authentication_string, password) = PASSWORD('amateur') OR IF(plugin='mysql_native_password', authentication_string, password) = PASSWORD(UPPER('amateur')) OR IF(plugin='mysql_native_password', authentication_string, password) = PASSWORD(CONCAT(UPPER(LEFT('amateur', 1)), SUBSTRING('amateur', 2, LENGTH('amateur'))))
```

When I run the query manually, I get:

```
mysql> SELECT CONCAT(user, '@', host) FROM mysql.user WHERE IF(plugin='mysql_native_password', authentication_string, password) = PASSWORD('amateur') OR IF(plugin='mysql_native_password', authentication_string, password) = PASSWORD(UPPER('amateur')) OR IF(plugin='mysql_native_password', authentication_string, password) = PASSWORD(CONCAT(UPPER(LEFT('amateur', 1)), SUBSTRING('amateur', 2, LENGTH('amateur'))));
ERROR 1054 (42S22): Unknown column 'password' in 'where clause'
```

Server version: 5.7.16 MySQL Community Server (GPL)
MacOS Mojave 10.14.4 Beta (18E205e)

**Comment by acs-ferreira** [comment] 2019-03-10 17:45
What version of the script are you running?
It should be fixed https://github.com/major/MySQLTuner-perl/issues/373

**Comment by tholu** [comment] 2019-03-11 17:06
I'm running version 1.7.15 / latest master. 

It seems that the fix described in the issue (https://github.com/major/MySQLTuner-perl/commit/ff2a47e4618326ede36ca8553981ac7c66ad36fd) was reverted (Current version: https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L1742). The `'` around `password` are missing.

This is the commit, where the fix was reverted: https://github.com/major/MySQLTuner-perl/commit/4c14ba97184fa03e4c94c5619eb017bf87d89e10 (related issue #412)

**Comment by simonhampel** [comment] 2019-03-13 20:42
I can confirm this issue.

I have two identical VPS machines (built from the same script), one was built a while ago and has MySQLTuner 1.7.14 running with no problems.

The newer machine got MySQLTuner 1.7.15 and has the errors described by @tholu 

I copied the 1.7.14 from the older machine to the newer machine and it works as expected.

1.7.15 is definitely broken.

**Comment by jmrenouard** [comment] 2019-03-14 10:01
Hi,

We have a fix for issue on several version MariaDB and MySQL.

This need a lot of test.

**Comment by tholu** [comment] 2019-03-14 10:43
@jmrenouard What's the status of Travis? Adding tests first is definitely the way to go, as there are multiple conflicting issues, and all of them need to be solved at the same time.

**Comment by Phobos-7** [comment] 2019-04-02 15:41
This is still a problem :(
I just manually added `'` around `password` to fix it on my servers.

**Comment by tholu** [comment] 2019-04-02 19:36
This can only be solved if a comprehensive set of tests is constantly running (on Travis). This should be priority no 1 to get running again. Otherwise things will break on all ends. We already have this flip-flop situation of bugs getting "fixed" which breaks other stuff, then the other way round.

**Comment by michelsup** [comment] 2019-05-23 09:44
> I just manually added `'` around `password` to fix it on my servers.

I did the trick for me as well.

**Comment by MattRiddell** [comment] 2019-06-26 01:12
Yep, putting speechmarks around password in this line fixed it for me too:

`"IF(plugin='mysql_native_password', authentication_string, 'password')";`

**Comment by tholu** [comment] 2019-06-26 14:50
Is there any interest in fixing this in a proper way, without breaking other things? @jmrenouard

**Comment by dvershinin** [comment] 2019-06-30 18:52
MySQL 5.7, the issue is there for me too.

**Comment by jmrenouard** [comment] 2019-10-01 22:50
Working fine for me on mysql 5.7

**Closed by jmrenouard** 2019-10-01 22:50 UTC
Labels: Test wanted, bug
