### ISSUE TITLE
disable column type to ENUM suggestion

### ISSUE THREAD

**Issue by mia0x75** [major/MySQLTuner-perl#356] opened 2017-11-21 02:31 UTC
When I try to run the following cmd
perl mysqltuner.pl --buffers --dbstat --idxstat --sysstat --pfstat

I get lots of data type to ENUM suggestions, and I think most of them meaningless. Such as

ENUM('0.00','100.00','327.00','500.00','600.00','900.00','1200.00','1500.00','15000.00')

**Comment by mia0x75** [comment] 2017-11-21 02:59
how about remove mysql_tables() ?

**Comment by streaky** [comment] 2017-11-27 22:10
I *partly* disagree with this, in some cases it's worth considering, the key point here is considering. I actually came to report the same but slightly different issue - it's okay to suggest this because sometimes it makes sense, the problem is it stops being useful if it's suggesting 15000 different ENUM() values. There should be a limit - if it tries to suggest suggest more than x (lets say 10 for argument sake then it just shouldn't suggest it). There should be a default setting of what's reasonable and it should be configurable and whatever is greater than that shouldn't be included.

Under any circumstance [this](https://gist.githubusercontent.com/streaky/891cd7014d82d314617e63011d582ab9/raw/7f7c21f678dc7cf9f17ea1bded25b9344a50b444/no-optimal-actually.txt) just shouldn't be a thing.

**Comment by mia0x75** [comment] 2017-11-28 02:44
I think we should use INT rather than ENUM in our database design, because it is not easy to add new value(s). But anyway, at least, we should add an option to disable this kind of check, or disabled by default.

**Comment by streaky** [comment] 2017-11-28 07:26
Sure, it's obviously massively dependant on circumstance. IMHO every single suggestion mysqltuner makes should be considered carefully and not blindly done.

I've been poking around this issue and I've found a couple of things.

- The tuner [uses](https://github.com/major/MySQLTuner-perl/blob/master/mysqltuner.pl#L5846) internal MySQL [functionality](https://dev.mysql.com/doc/refman/5.7/en/procedure-analyse.html)
- The settings for that function that tuner sets appear to be way too high, it is set by default at 256 elements which even that seems way too high to me, tuner uses a 10,000 element setting. IMHO this is just wrong and why it produces fairly trash suggestions
- The function is deprecated from 5.7.18, and removed in 8.0. It isn't long for this world.
- Even if you reduce the number of max elements (say to 10) it sometimes bugs and ignores the max element setting anyway, thus is arguably unfixable - but it does reduce the noise

Really it probably needs some sort of custom column data type handler that can make better suggestions. Some people have [done some work](https://github.com/shlomi-noach/openarkkit/blob/master/openarkkit/src/oak/oak-show-limits.py#L61) on creating an alternative that's arguably in some ways more useful that could potentially be ported into tuner and possibly expanded upon, replacing PROCEDURE ANALYSE with something more useful.

Just some thoughts and things I've found.

**Comment by jmrenouard** [comment] 2017-11-28 08:29
Hi,

Advices for ENUM is coming from server himself with PROCEDURE ANALYSE.

SELECT $_ FROM $dbname.$tbname PROCEDURE ANALYSE(100000)

**Comment by jmrenouard** [comment] 2018-09-25 15:16
Hi @streaky Hi @mia0x75 

Want do you want me to do on this feature ?
* Remove it
* Silent it by default
* Reduce sample analysis
* Remove all ENUM preconisations 
* Disabling it by default on MySQL 8.

Thanks for your feedback

**Comment by leewin12** [comment] 2019-04-19 04:39
Hi @jmrenouard 

If you don't mind, I would like to suggest `Remove it` or `Remove all ENUM preconisations`.

Thank you for your effort on awesome tool.

**Comment by streaky** [comment] 2019-04-19 14:32
Hm, didn't see this notification when the original reply was, weird.

Certainly in 8.0 it's removed so it needs disabling for 8.0.

Secondly using 100000 for max elements seems completely wrong. The default is 256 and that's more sane but there's an argument that says it should be 10 or 20, something in that area. Personally I'd say - and this is a personal thing - that it's only really useful on a table with a decent number of rows. You can only draw reasonable conclusions about this stuff automatically if you have enough data and not too many elements. If you want to make it awesome maybe (these values would take some tweaking, just an initial thought) say minimum of 20 rows and set max_elements at say 10% of the number of rows or a 1000 depending on which is smaller. That way you'd kind of force it to give reasonable answers. You'd still have to have a think about if that's right and it'd give you false negatives in some cases but those false negatives I'd argue would be out of scope anyway.

**Comment by jmrenouard** [comment] 2019-10-01 22:45
REmoving check for mysql 8.0 and percona 8.0.
Procedure anlyse() has be removed since version 8.0 on both distributions.

**Closed by jmrenouard** 2019-10-01 22:45 UTC
Labels: Questions, enhancement
