### ISSUE TITLE
Attempted to use login credentials, but they were invalid.

### ISSUE THREAD

**Issue by youraveragejoe** [major/MySQLTuner-perl#248] opened 2016-09-21 19:47 UTC
My server is running webuzo and I made the switch from MySQL 5.6 to MariaDB10.1 . Now I get the error message saying the login credentials are invalid. 
I know they aren't as before, in MySQL 5.6 I was able to use it and am able to use it in phpmyadmin as well.
How could I fix this issue?

Thank you.

**Comment by jmrenouard** [comment] 2016-09-22 13:23
Hi @youraveragejoe 

Is it working using --pass option ?

Thanks for your feedback.
@jmrenouard

**Comment by youraveragejoe** [comment] 2016-09-23 14:06
Hi,

Thank you for your answer.  I've even tried a fresh install of webuzo with mariadb but still not working with mysqltuner.pl. My version is : MariaDB10.1

I've tried: 

perl mysqltuner.pl --user wp390 --pass 'C[Q7w!A03S'
perl mysqltuner.pl --host 127.0.0.1 --user wp390 --pass 'C[Q7w!A03S'

and a few other variations, mentioning port, using localhost instead of 127.0.0.1 but still no results

 >>  MySQLTuner 1.6.18 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
[!!] Attempted to use login credentials, but they were invalid

**Comment by jmrenouard** [comment] 2016-09-26 11:25
Hi @youraveragejoe 

Can you try this :
perl mysqltuner.pl --user wp390 --pass 'C\[Q7w\!A03S'

BTW, can you change also your password ?
This tracker is public and everybody know your password now ;)

@jmrenouard

**Comment by youraveragejoe** [comment] 2016-10-05 06:37
Hi,


Sorry for my late reply. I've tried but it doesn't work. Those details weren't my real db details, I've edited them before posting, I just let it similar to see length of password and so on.

[!!] Attempted to use login credentials, but they were invalid

________________________________

**Comment by youraveragejoe** [comment] 2016-10-06 09:07
Hi,

The only thing I can think of different is this, when I type: netstat -tlpn:

tcp6       0      0 :::3306                 :::*                    LISTEN      3567/mysqld

It shows tcp6 not regular tcp, could this be it?

**Comment by jmrenouard** [comment] 2016-10-06 16:00
Hi @youraveragejoe 

What provides command  netstat -xlpn ?

Maybe you can use --host option in order to force TCP socket usage.

@jmrenouard

**Comment by youraveragejoe** [comment] 2016-10-07 05:54
Hi Jmrenouard,

This is what I get on my config ( webuzo+mariadb 10.1+php7+nginx ):

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      3895/nginx: master
tcp        0      0 0.0.0.0:2002            0.0.0.0:*               LISTEN      3979/nginx: master
tcp        0      0 0.0.0.0:2003            0.0.0.0:*               LISTEN      3979/nginx: master
tcp        0      0 0.0.0.0:2004            0.0.0.0:*               LISTEN      3979/nginx: master
tcp        0      0 0.0.0.0:2005            0.0.0.0:*               LISTEN      3979/nginx: master
tcp        0      0 0.0.0.0:21              0.0.0.0:*               LISTEN      3894/pure-ftpd (SER
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      32016/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      4035/master
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      3895/nginx: master
tcp        0      0 127.0.0.1:8999          0.0.0.0:*               LISTEN      3933/perl
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      3947/php-fpm: maste
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      3947/php-fpm: maste
tcp6       0      0 :::21                   :::*                    LISTEN      3894/pure-ftpd (SER
tcp6       0      0 :::22                   :::*                    LISTEN      32016/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      4035/master
tcp6       0      0 :::3306                 :::*                    LISTEN      3909/mysqld

**Comment by jmrenouard** [comment] 2016-10-07 09:45
Hi @youraveragejoe 

I think you will be able to connect throught your IPv6 port with --host option.

Thanks for your feedback
@jmrenouard

**Comment by youraveragejoe** [comment] 2016-10-07 10:40
Hi @jmrenouard,

Thank you for you suggestion. I' tried and used the ip or domain with forcemem as well but still says wrong password

**Comment by jmrenouard** [comment] 2016-10-10 11:26
Hi @youraveragejoe 

Do you try to use .my.cnf or .mylogin.cnf approach to store your password ?
IMHO, I think this is a more secure approach for this issue.
Clear password are actually stored in the .bash_history file. So this is not a so good approach as it's seems.

@jmrenouard

**Comment by youraveragejoe** [comment] 2016-10-10 13:02
Hi jmrenouard,

I think I've gotten to the bottom of this and it wasn't a bug, it was just a stupid mistake. The optimization rules, something like:

query_cache_type =1
join_buffer_size=512K
tmp_table_size=64M
max_heap_table_size=64M
thread_cache_size=-1
innodb_buffer_pool_size= 4096M
innodb_buffer_pool_instances=1

in my case were put under [client-server] in webuzo thus when trying to:

 mysqladmin ping
the answer was:
mysqladmin: unknown variable 'query_cache_type=1'

after putting them in the correct place the answer to the command was:

mysqladmin --version
mysqladmin  Ver 9.1 Distrib 10.1.18-MariaDB, for Linux on x86_64


I just had to put the optimization rules under

[mysqld]
and everything is working now.

If anyone is dealing with this hope it helps, it's not a bug it's just putting instructions in a wrong place.

**Comment by jmrenouard** [comment] 2016-10-18 13:03
Hi @youraveragejoe 

Thanks for sharing experience with mysqltuner.

Hope this issue can help MT user to get a faster answers to similar question.

I close this issue.

**Closed by jmrenouard** 2016-10-18 13:03 UTC
Labels: Help Wanted, Questions

**Comment by ryanjbonnell** [comment] 2017-05-07 23:25
For anyone else having this problem and getting the MySQLTuner error:

> **[!!]** Attempted to use login credentials, but they were invalid

Check the validity of your `my.cnf` file by running the following Terminal command:

`$mysqladmin ping`

If everything is healthy, you'll get a response similar to:

`mysqld is alive`

In my case, I was unable to login due to an unknown MySQL variable, which was indicated by:

```
$mysqladmin ping
mysqladmin: unknown variable 'max_allowed_packet=1073741824'
```

Inspecting the contents of `/etc/my.cnf` showed:

```
...

# This group is read both both by the client and the server
# use it for options that affect everything
#
[client-server]
max_allowed_packet = 1073741824
```

Removing the invalid variable and restarting MySQL fixed the issue and allowed me to successfully login via MySQLTuner:

`$ mysqltuner --host 127.0.0.1 --port 3306 --user root --noask`

Tested on macOS 10.12.4 "Sierra", MariaDB 10.1.22 and MySQLTuner 1.6.18.

**Comment by w3hr** [comment] 2018-10-02 22:58
i tried for like 10 mins, this script told me everytime i have wrong credentials, 
I have questioned myself, then i remember my old days in perl ... so if u got $$$ in your passwords or other 
special characters, dont waste your time, use backslash (\) to escape them, good night

**Comment by armpdq** [comment] 2018-10-25 09:06
> i tried for like 10 mins, this script told me everytime i have wrong credentials,
> I have questioned myself, then i remember my old days in perl ... so if u got $$$ in your passwords or other
> special characters, dont waste your time, use backslash () to escape them, good night

same issue, mysql 5.7 require strong password and mysqltuner is not usable anymore. any options to fix ?

**Comment by jmrenouard** [comment] 2018-10-26 06:39
Hi 

MySQL 8 is using mysql_config_editor for credentials.

Best regards

**Comment by huadaonan** [comment] 2022-01-20 02:52
i have meet the same problem, maybe the host parse reason,when i change host from localhost to 127.0.0.1,and add socket address. that can be run. like this


perl mysqltuner.pl --defaults-file xxx  --mysqladmin xxx --mysqlcmd xxx  --user root  --pass 'xxx' --host 127.0.0.1 --port 3306 --socket xx/mysqld.sock
perl mysqltuner.pl --defaults-file xxx  --mysqladmin xxx --mysqlcmd xxx  --user root  --pass 'xxx'  --port 3306 --socket xx/mysqld.sock

**Comment by huadaonan** [comment] 2022-01-20 02:53
my version is 1.8.7

**Comment by pioneerpathan** [comment] 2022-10-08 09:07
> Hi jmrenouard,
> 
> I think I've gotten to the bottom of this and it wasn't a bug, it was just a stupid mistake. The optimization rules, something like:
> 
> query_cache_type =1 join_buffer_size=512K tmp_table_size=64M max_heap_table_size=64M thread_cache_size=-1 innodb_buffer_pool_size= 4096M innodb_buffer_pool_instances=1
> 
> in my case were put under [client-server] in webuzo thus when trying to:
> 
> mysqladmin ping the answer was: mysqladmin: unknown variable 'query_cache_type=1'
> 
> after putting them in the correct place the answer to the command was:
> 
> mysqladmin --version mysqladmin Ver 9.1 Distrib 10.1.18-MariaDB, for Linux on x86_64
> 
> I just had to put the optimization rules under
> 
> [mysqld] and everything is working now.
> 
> If anyone is dealing with this hope it helps, it's not a bug it's just putting instructions in a wrong place.

Hello folks, 

I had the same issue. as @youraveragejoe said, I try with `mysqladmin ping` and catch error that was in my.cnf file. I removed the unknown variable line and it worked like a charm.

Thanks.

**Comment by mikeg-de** [comment] 2025-01-30 13:42
I faced the same issue but the cause was the presence of an `&` in my password. Updating that and, if executing mysqltuner still fails, enclosing the password in single quotes, did work for me.

**Comment by orzel** [comment] 2025-03-29 17:36
Hit by this as well. mysqltuner would fail to connect whatever i do, without any explicit message about configuration being bad.
Testing with `mysql -u root -p` on the server does provide a very clear message about what is wrong with the config : try that if you encounter this problem.
