### ISSUE TITLE
FAIL Execute SQL / return code: 256

### ISSUE THREAD

**Issue by KarelWintersky** [major/MySQLTuner-perl#442] opened 2019-07-06 16:22 UTC
A lot of reports like this:
```
[!!] FAIL Execute SQL / return code: 256
[!!] failed to execute: SELECT CONCAT(user, '@', host) FROM mysql.user WHERE IF(plugin='mysql_native_password', authentication_string, password) = PASSWORD('38') OR IF(plugin='mysql_native_password', authentication_string, password) = PASSWORD(UPPER('38')) OR IF(plugin='mysql_native_password', authentication_string, password) = PASSWORD(CONCAT(UPPER(LEFT('38', 1)), SUBSTRING('38', 2, LENGTH('38'))))
[!!] FAIL Execute SQL / return code: 256
```

ubuntu 16.04
MySQLTuner version  1.7.15
mysql  Ver 14.14 Distrib 5.7.26

**Comment by raatti** [comment] 2019-07-12 11:38
See: https://stackoverflow.com/questions/36501682/mysqltuner-failed-return-code-256

**Comment by raatti** [comment] 2019-07-12 11:41
It sounds like authentication/connection issue.

**Comment by raatti** [comment] 2019-07-12 11:44
Duplicate of #427 ?

**Comment by KarelWintersky** [comment] 2019-07-12 14:26
May be. 
Solution required

**Comment by mozzee** [comment] 2019-07-30 21:47
A dirty fix would be to update mysql user table for missing columns

ALTER TABLE `user` ADD `Create_tablespace_priv` ENUM('N','Y') NOT NULL DEFAULT 'N' AFTER `Trigger_priv`; 
ALTER TABLE `user` ADD `plugin` CHAR(64) NULL AFTER `max_user_connections`; 
ALTER TABLE `user` ADD `authentication_string` TEXT NULL DEFAULT NULL AFTER `plugin`; 
ALTER TABLE `user` ADD `password_expired` ENUM('N','Y') NOT NULL DEFAULT 'N' AFTER `authentication_string`;

**Comment by cC-Xx** [comment] 2019-09-26 12:41
can you please check this patch out? 
hope it will help ... 

# cat /usr/ports/databases/mysqltuner/files/patch-mysqltuner.pl 
--- mysqltuner.pl.orig  2019-09-25 17:34:50.547651000 +0300
+++ mysqltuner.pl       2019-09-25 17:35:28.725401000 +0300
@@ -1739,7 +1739,7 @@
     my $PASS_COLUMN_NAME = 'password';
     if ( $myvar{'version'} =~ /5\.7|10\..*MariaDB*/ ) {
         $PASS_COLUMN_NAME =
-"IF(plugin='mysql_native_password', authentication_string, password)";
+"IF(plugin='mysql_native_password', authentication_string, 'password')";
     }
     debugprint "Password column = $PASS_COLUMN_NAME";
 
thanx

**Comment by jmrenouard** [comment] 2019-10-01 22:42
Hi,
MySQLtuner password checks are working fine on mysql 5.7. and mariaDB 10.0/10.1/10.2/10.3/10.4.

I close this issue and version 1.7.17 is ok for me.

**Closed by jmrenouard** 2019-10-01 22:42 UTC
Labels: Help Wanted, bug
