### ISSUE TITLE
InnoDB Read buffer efficiency not correct

### ISSUE THREAD

**Issue by giponino** [major/MySQLTuner-perl#740] opened 2023-10-11 16:16 UTC
Hi, I'm on MySQLTuner 2.3.2 and MariaDB 10.11.5, InnoDB Read buffer efficiency is not calculated correctly:

[OK] InnoDB buffer pool / data size: 1.5G / 602.1M
[OK] Ratio InnoDB log file size / InnoDB Buffer pool size: 375.0M * 1/1.5G should be equal to 25%
[--] Number of InnoDB Buffer Pool Chunk: 64 for 1 Buffer Pool Instance(s)
[OK] Innodb_buffer_pool_size aligned with Innodb_buffer_pool_chunk_size & Innodb_buffer_pool_instances
**[!!] InnoDB Read buffer efficiency: 0% (-33094 hits / 0 total)**

**Comment by bfontaine** [comment] 2023-11-08 15:07
I have the same issue with MariaDB 10.9.8 and the same version of MySQLTuner:

```
…
[OK] Innodb_buffer_pool_size aligned with Innodb_buffer_pool_chunk_size & Innodb_buffer_pool_instances
[!!] InnoDB Read buffer efficiency: 0% (-703802 hits / 0 total)
[OK] InnoDB Write Log efficiency: 98.19% (1303757356 hits / 1327825158 total)
[OK] InnoDB log waits: 0.00% (0 waits / 24067802 writes)
```

**Comment by fidoboy** [comment] 2023-11-26 20:53
To solve this stupid issue do this:

Line 3181 and change "percentage(" into "100-percentaje("

solved :)

**Comment by bfontaine** [comment] 2023-11-30 09:41
@fidoboy better do a pull request so everybody benefits from the fix :wink:

**Comment by jmrenouard** [comment] 2023-11-30 09:51
Hi @fidoboy @bfontaine @giponino 

Efficiency calculation:
number of read found in Buffer pool * 100 / number of read

[Innodb_buffer_pool_read_requests](http://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Innodb_buffer_pool_read_requests) indicates the number of logical read requests (read from memory) InnoDB has done.

[Innodb_buffer_pool_reads](http://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Innodb_buffer_pool_reads) indicates the number of logical reads that InnoDB could not satisfy from the buffer pool, and had to read directly from the disk (physical reads).

The InnoDB Buffer Pool hit ratio is a indicator how often your pages are retrieved from memory instead of disk:

Innodb_buffer_pool_read_requests / (Innodb_buffer_pool_read_requests + Innodb_buffer_pool_reads) * 100 = InnoDB Buffer Pool hit ratio

**Comment by jmrenouard** [comment] 2023-11-30 10:09
In this issue, it seems to be an issue related to MariaDB
-703802 hits is not possible in a real world, we can't get negative number of reads

**Comment by fidoboy** [comment] 2023-11-30 16:35
> @jmrenouard The data seems right in MariaDB:
> 
> ```
> $ sudo mysql
> MariaDB [(none)]> show status where variable_name like 'Innodb_buffer_pool_read%s';
> +----------------------------------+---------+
> | Variable_name                    | Value   |
> +----------------------------------+---------+
> | Innodb_buffer_pool_read_requests | 0       |
> | Innodb_buffer_pool_reads         | 1123753 |
> +----------------------------------+---------+
> 2 rows in set (0.000 sec)
> 
> MariaDB [(none)]> show global status where variable_name like 'Innodb_buffer_pool_read%s';
> +----------------------------------+---------+
> | Variable_name                    | Value   |
> +----------------------------------+---------+
> | Innodb_buffer_pool_read_requests | 0       |
> | Innodb_buffer_pool_reads         | 1123753 |
> +----------------------------------+---------+
> 2 rows in set (0.001 sec)
> ```
> 
> MySQLTuner agrees:
> 
> ```
> $ sudo ./mysqltuner.pl --debug | grep Innodb_buffer_pool_read.*s
> [DG]  * Innodb_buffer_pool_read_requests = 0
> [DG]  * Innodb_buffer_pool_reads = 1123753
> [DG]  * Innodb_buffer_pool_read_requests = 0
> [DG]  * Innodb_buffer_pool_reads = 1123753
> [DG] Innodb_buffer_pool_reads: 1123753
> [DG] Innodb_buffer_pool_read_requests: 0
> ```
> 
> However the report somehow shows that value in negative:
> 
> `[!!] InnoDB Read buffer efficiency: 0% (-1123753 hits / 0 total)`
> 
> I don’t see any substraction happen with this value in `mysqltuner.pl` nor anything that could explain the issue.
> 
> @fidoboy your change seems to be irrelevant to this issue, as it affects only the percentage and not the bad value.

Well, your test is wrong because you haven't done already my change. Fix the code into that line that I've said and you'll have the right value.

**Comment by jmrenouard** [comment] 2023-11-30 17:12
Hi, can you test last commit ?
It seems to be the right way now

**Comment by bfontaine** [comment] 2023-11-30 17:32
I can confirm that it works now, thank you @jmrenouard! I couldn’t see the bad code because I was looking at the latest `master` version.

**Comment by jmrenouard** [comment] 2023-11-30 21:44
Hi,
Thanks for your precious help, feedbacks and this discussion

I close this issue feel free to reopen if you feel it ;)

**Closed by jmrenouard** 2023-11-30 21:44 UTC
